version: "3.8"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "39002:80"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./raven_web_app
    networks:
      - raven-dashboard

  api:
    build:
      dockerfile: Dockerfile
      context: ./raven_rest_api
    networks:
      - raven-dashboard
    depends_on:
      - db-server
      - redis-server

  db-server:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - raven-dashboard
    volumes:
      - db-storage:/data/db

  redis-server:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    networks:
      - raven-dashboard

networks:
  raven-dashboard:
    driver: bridge
volumes:
  db-storage:
    driver: local
